version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: smartmealbuddy-db
    environment:
      POSTGRES_DB: smartmealbuddy
      POSTGRES_USER: smartmealbuddy
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartmealbuddy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartmealbuddy-api
    environment:
      DATABASE_URL: "postgresql://smartmealbuddy:password123@postgres:5432/smartmealbuddy"
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
      JWT_EXPIRES_IN: "7d"
      SPOONACULAR_API_KEY: "your-spoonacular-api-key"
      PORT: 5000
      NODE_ENV: "development"
      FRONTEND_URL: "http://localhost:3000"
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartmealbuddy-web
    environment:
      REACT_APP_API_URL: "http://localhost:5000/api"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data:
